# boms/deployment.yaml
version: "3.0.6"
change_request: "CR-12345"
created_by: "your-name"

# Shared server configuration for all deployments in this BOM
source_server: dev-ppm-useast
target_server: test-ppm-useast

# --- BASELINE DEPLOYMENT (Optional) ---
# The pipeline will run this section first.
baseline:
  enabled: true # Controls whether this section runs
  profile: baseline
  description: "Baseline entity sync for new project setup."
  rollback_pipeline_id: 12344 # ID of a previous, successful pipeline to restore

# --- FUNCTIONAL DEPLOYMENT (Optional) ---
# The pipeline will run this section second, after baseline.
functional:
  enabled: true # Controls whether this section runs
  profile: functional-cd
  description: "Deploy new incident management workflow."
  rollback_pipeline_id: local # ID of a previous, successful pipeline to restore
  entities:
    - entity_id: 9
      reference_code: "WF_INCIDENT_MGMT"
      entity_type: "Workflow"
      description: "Incident management workflow"
