# Production Deployment Configuration
# This is the default configuration used in production CI/CD pipelines
# For local testing, create deployment-config.local.yaml to override these settings

# kMigrator real installation paths (remote execution on PPM servers)
kmigrator:
  extract_script: "/opt/ppm/bin/kMigratorExtract.sh"
  import_script: "/opt/ppm/bin/kMigratorImport.sh"

deployment:
  bundle_dir: "./bundles"
  archive_dir: "./archives"
  storage_backend: "s3"  # S3 storage (bundles go directly: PPM → S3 → PPM)

csm:
  component_url: "eros.butterflycluster.com/staging/vault-secret-fetcher/vault-retrieve"
  component_version: "2.0.0"

s3:
  bucket_name: "ppm-deployment-bundles"
  region: "us-east-1"
  prefix: "bundles/"
  endpoint_url: "http://phobos:9002"
  vault_roles:
    - name: s3-read
      path: secret/data/shared/s3

servers:
  dev-ppm-useast:
    url: "https://ppm-dev.company.com"
    env_type: dev
    region: useast
    ssh_host: "mars"
    ssh_env_vars:
      username: "SSH_USERNAME"
      password: "SSH_PASSWORD"
    ppm_api_env_vars:
      username: "PPM_ADMIN_USER"
      password: "PPM_ADMIN_PASSWORD"
    vault_roles:
      - name: ssh-infra
        path: secret/data/infrastructure/ssh/mars
      - name: ppm-dev
        path: secret/data/ppm/dev/useast

  test-ppm-useast:
    url: "https://ppm-test.company.com"
    env_type: test
    region: useast
    ssh_host: "phobos"
    ssh_env_vars:
      username: "SSH_USERNAME"
      password: "SSH_PASSWORD"
    ppm_api_env_vars:
      username: "PPM_ADMIN_USER"
      password: "PPM_ADMIN_PASSWORD"
    vault_roles:
      - name: ssh-infra
        path: secret/data/infrastructure/ssh/phobos
      - name: ppm-test
        path: secret/data/ppm/test/useast

  staging-ppm-useast:
    url: "https://ppm-staging.company.com"
    env_type: staging
    region: useast
    ssh_host: "cygnus"
    ssh_env_vars:
      username: "SSH_USERNAME"
      password: "SSH_PASSWORD"
    ppm_api_env_vars:
      username: "PPM_ADMIN_USER"
      password: "PPM_ADMIN_PASSWORD"
    vault_roles:
      - name: ssh-infra
        path: secret/data/infrastructure/ssh/cygnus
      - name: ppm-staging
        path: secret/data/ppm/staging/useast

  prod-ppm-useast:
    url: "https://ppm-prod.company.com"
    env_type: prod
    region: useast
    ssh_host: "helios"
    ssh_env_vars:
      username: "SSH_USERNAME"
      password: "SSH_PASSWORD"
    ppm_api_env_vars:
      username: "PPM_ADMIN_USER"
      password: "PPM_ADMIN_PASSWORD"
    vault_roles:
      - name: ssh-infra
        path: secret/data/infrastructure/ssh/helios
      - name: ppm-prod
        path: secret/data/ppm/prod/useast
