# Production Deployment Configuration
# This is the default configuration used in production CI/CD pipelines
# For local testing, create deployment-config.local.yaml to override these settings

# kMigrator real installation paths (remote execution on PPM servers)
kmigrator:
  extract_script: "/opt/ppm/bin/kMigratorExtract.sh"
  import_script: "/opt/ppm/bin/kMigratorImport.sh"

# Deployment settings
deployment:
  bundle_dir: "./bundles"
  archive_dir: "./archives"
  storage_backend: "s3"  # S3 storage (bundles go directly: PPM → S3 → PPM)

# S3/MinIO configuration
s3:
  bucket_name: "ppm-deployment-bundles"
  region: "us-east-1"
  prefix: "bundles/"
  endpoint_url: "http://phobos:9002"
  # Credentials from environment: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY

# PPM Server Registry with SSH configuration for remote execution
# Credentials injected from GitLab CI/CD environment variables (via Vault):
#
# Environment-specific (vault: secret/data/ppm/{env}/useast):
#   - PPM_SERVICE_ACCOUNT_USER: Service account username (used for both PPM API and SSH)
#   - PPM_SERVICE_ACCOUNT_PASSWORD: Service account password (used for both PPM API and SSH)
#
# Shared across all environments (vault: secret/data/shared/s3):
#   - ACCESS_KEY_ID → exported as AWS_ACCESS_KEY_ID
#   - SECRET_ACCESS_KEY → exported as AWS_SECRET_ACCESS_KEY
servers:
  dev-ppm-useast:
    url: "https://ppm-dev.company.com"
    env_type: dev
    region: useast
    ssh_host: "ppm-dev-internal.company.com"
    ci_vault_configs: |
      - VAULT_ROLE: ppm-dev
        VAULT_PATH: secret/data/ppm/dev/useast
      - VAULT_ROLE: s3-read
        VAULT_PATH: secret/data/shared/s3
        PREFIX: AWS_

  test-ppm-useast:
    url: "https://ppm-test.company.com"
    env_type: test
    region: useast
    ssh_host: "ppm-test-internal.company.com"
    ci_vault_configs: |
      - VAULT_ROLE: ppm-test
        VAULT_PATH: secret/data/ppm/test/useast
      - VAULT_ROLE: s3-read
        VAULT_PATH: secret/data/shared/s3
        PREFIX: AWS_

  staging-ppm-useast:
    url: "https://ppm-staging.company.com"
    env_type: staging
    region: useast
    ssh_host: "ppm-staging-internal.company.com"
    ci_vault_configs: |
      - VAULT_ROLE: ppm-staging
        VAULT_PATH: secret/data/ppm/staging/useast
      - VAULT_ROLE: s3-read
        VAULT_PATH: secret/data/shared/s3
        PREFIX: AWS_

  prod-ppm-useast:
    url: "https://ppm-prod.company.com"
    env_type: prod
    region: useast
    ssh_host: "ppm-prod-internal.company.com"
    ci_vault_configs: |
      - VAULT_ROLE: ppm-prod
        VAULT_PATH: secret/data/ppm/prod/useast
      - VAULT_ROLE: s3-read
        VAULT_PATH: secret/data/shared/s3
        PREFIX: AWS_
      - VAULT_ROLE: smtp-read
        VAULT_PATH: secret/data/shared/smtp
