# Deployment Governance Rules
# Defines critical validation rules for BOM deployments
# Philosophy: Prevent production outages, data leaks, and security issues

version: "1.0.0"

# ==============================================================================
# CRITICAL RULES (Day 1)
# ==============================================================================

# Enforce sequential deployment promotion order
deployment_promotion_order:
  enabled: true
  severity: blocking
  # Define promotion sequence - strict sequential promotion enforced (no skipping)
  # Current environments: dev -> test -> staging -> prod
  sequence: [dev, test, staging, prod]
  message: "Deployments must follow strict promotion order: dev → test → staging → prod (no skipping)"

# All deployments require rollback capability
require_prod_rollback:
  enabled: true
  applies_to: [dev, test, uat, staging, prod]
  severity: blocking
  message: "All deployments must specify rollback_pipeline_id (enables recovery from mistakes)"

# Production deployments require change request
require_prod_change_request:
  enabled: true
  applies_to: [prod, staging]
  severity: blocking
  message: "Production deployments must specify change_request"

# Source and target must be different servers
prevent_same_server:
  enabled: true
  severity: blocking
  message: "Source and target servers must be different"

# Branch-environment alignment
# Ensures BOM target_server matches the branch deployment environment
require_branch_environment_match:
  enabled: true
  severity: blocking
  message: "BOM target_server does not match branch environment"
  mappings:
    # feature/* branches deploy FROM dev TO test
    feature:
      allowed_env_types: [test]

    # develop branch deploys FROM test TO staging
    develop:
      allowed_env_types: [staging]

    # main branch deploys FROM staging TO prod
    main:
      allowed_env_types: [prod]

# ==============================================================================
# FUTURE RULES (Disabled by default - enable when ready)
# ==============================================================================

# Limit deployment size
max_entities_per_deployment:
  enabled: false
  limit: 50
  severity: warning
  message: "Large deployments are harder to troubleshoot. Consider splitting."