# templates/child-pipeline-template.yml
# This is a template for the dynamically generated child pipeline.
# The generator script will replace %%SOURCE_ROLE%% and %%TARGET_ROLE%%.

# Global defaults - runs before all jobs
default:
  before_script:
    - dnf install -y -q wget curl

stages:
  - extract
  - import
  - archive

# Base template for common setup (dnf installs, etc.)
.job_base:
  image: almalinux:8
  before_script:
    - dnf install -y -q git bash openssh-clients sshpass wget curl
    - dnf module reset -y python36
    - dnf install -y -q python3.11 python3.11-pip python3.11-devel
    - pip3.11 install PyYAML boto3 --quiet
    - ln -sf /usr/bin/python3.11 /usr/bin/python3

extract:
  extends:
    - .job_base
    - .vault-%%SOURCE_ROLE%%  # Placeholder for the source role
    - .vault-s3
  stage: extract
  script:
    - echo "Executing EXTRACT stage..."
    - python3 tools/deploy.py extract --type $DEPLOYMENT_TYPE --bom $BOM_FILE
  artifacts:
    paths:
      - bundles/*.yaml
    expire_in: 1 hour

import:
  extends:
    - .job_base
    - .vault-%%TARGET_ROLE%%  # Placeholder for the target role
    - .vault-s3
  stage: import
  script:
    - echo "Executing IMPORT stage..."
    - python3 tools/deploy.py import --type $DEPLOYMENT_TYPE --bom $BOM_FILE
  needs: [extract]

archive:
  extends:
    - .job_base
    - .vault-%%TARGET_ROLE%%  # Placeholder for the target role
    - .vault-s3
  stage: archive
  script:
    - echo "Executing ARCHIVE stage..."
    - python3 tools/deploy.py archive --type $DEPLOYMENT_TYPE --bom $BOM_FILE
  needs: [extract, import]
  artifacts:
    paths:
      - archives/*.yaml
      - evidence/
    expire_in: 1 year
