# .gitlab-ci-template.yml
# This is a reusable workflow for a single deployment type (e.g., baseline or functional).
# It is triggered by the main .gitlab-ci.yml file.

stages:
  - extract
  - import
  - archive

# Default configuration
default:
  image: almalinux:8
  before_script:
    # Install Python 3.11 from standard DNF repositories
    - dnf install -y -q git bash
    - dnf module reset -y python36
    - dnf install -y -q python3.11 python3.11-pip python3.11-devel
    - pip3.11 install PyYAML --quiet
    - ln -sf /usr/bin/python3.11 /usr/bin/python3

variables:
  # DEPLOYMENT_TYPE and BOM_FILE are passed in from the parent pipeline
  DEPLOYMENT_TYPE: "not-set"
  BOM_FILE: "not-set"

extract:
  stage: extract
  script:
    - echo "Executing EXTRACT stage for $DEPLOYMENT_TYPE..."
    - python3 tools/deploy.py extract --type $DEPLOYMENT_TYPE --bom $BOM_FILE
  artifacts:
    paths:
      - bundles/
    expire_in: 1 hour

import:
  stage: import
  script:
    - echo "Executing IMPORT stage for $DEPLOYMENT_TYPE..."
    - python3 tools/deploy.py import --type $DEPLOYMENT_TYPE --bom $BOM_FILE
  needs: [extract]

archive:
  stage: archive
  script:
    - echo "Executing ARCHIVE stage for $DEPLOYMENT_TYPE..."
    - python3 tools/deploy.py archive --type $DEPLOYMENT_TYPE --bom $BOM_FILE
  needs:
    - extract  # Need artifacts (bundles + metadata)
    - import   # Need to run after import completes
  artifacts:
    paths:
      - archives/
      - evidence/
    expire_in: 1 year
